### ISSUE TITLE
Fails to start with activated silerovad on raspi 4

### ISSUE THREAD

**Issue by cburghardt** [synesthesiam/homeassistant-satellite#21]
When I try to include --vad silero in the start then I get the following error.
It's a raspi 4 with raspbian 11

`Oct 15 11:26:29 hyperion systemd[1]: Started Home Assistant Satellite.
Oct 15 11:26:30 hyperion run[3481]: CRITICAL:root:Please pip install homeassistant_satellite[silerovad]
Oct 15 11:26:30 hyperion run[3481]: ERROR:__main__:Unexpected error in _mic_proc
Oct 15 11:26:30 hyperion run[3481]: Traceback (most recent call last):
Oct 15 11:26:30 hyperion run[3481]:   File "/home/pi/homeassistant-satellite/.venv/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
Oct 15 11:26:30 hyperion run[3481]:     from . import multiarray
Oct 15 11:26:30 hyperion run[3481]:   File "/home/pi/homeassistant-satellite/.venv/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
Oct 15 11:26:30 hyperion run[3481]:     from . import overrides
Oct 15 11:26:30 hyperion run[3481]:   File "/home/pi/homeassistant-satellite/.venv/lib/python3.9/site-packages/numpy/core/overrides.py", line 8, in <module>
Oct 15 11:26:30 hyperion run[3481]:     from numpy.core._multiarray_umath import (
Oct 15 11:26:30 hyperion run[3481]: ImportError: libcblas.so.3: cannot open shared object file: No such file or directory
Oct 15 11:26:30 hyperion run[3481]: During handling of the above exception, another exception occurred:
Oct 15 11:26:30 hyperion run[3481]: Traceback (most recent call last):
Oct 15 11:26:30 hyperion run[3481]:   File "/home/pi/homeassistant-satellite/homeassistant_satellite/__main__.py", line 276, in _mic_proc
Oct 15 11:26:30 hyperion run[3481]:     vad = SileroVoiceActivityDetector(args.vad_model)
Oct 15 11:26:30 hyperion run[3481]:   File "/home/pi/homeassistant-satellite/homeassistant_satellite/vad.py", line 27, in __init__
Oct 15 11:26:30 hyperion run[3481]:     import numpy as np
Oct 15 11:26:30 hyperion run[3481]:   File "/home/pi/homeassistant-satellite/.venv/lib/python3.9/site-packages/numpy/__init__.py", line 139, in <module>
Oct 15 11:26:30 hyperion run[3481]:     from . import core
Oct 15 11:26:30 hyperion run[3481]:   File "/home/pi/homeassistant-satellite/.venv/lib/python3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
Oct 15 11:26:30 hyperion run[3481]:     raise ImportError(msg)
Oct 15 11:26:30 hyperion run[3481]: ImportError:
Oct 15 11:26:30 hyperion run[3481]: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Oct 15 11:26:30 hyperion run[3481]: Importing the numpy C-extensions failed. This error can happen for
Oct 15 11:26:30 hyperion run[3481]: many reasons, often due to issues with your setup or how NumPy was
Oct 15 11:26:30 hyperion run[3481]: installed.
Oct 15 11:26:30 hyperion run[3481]: We have compiled some common reasons and troubleshooting tips at:
Oct 15 11:26:30 hyperion run[3481]:     https://numpy.org/devdocs/user/troubleshooting-importerror.html
Oct 15 11:26:30 hyperion run[3481]: Please note and check the following:
Oct 15 11:26:30 hyperion run[3481]:   * The Python version is: Python3.9 from "/home/pi/homeassistant-satellite/.venv/bin/python3"
Oct 15 11:26:30 hyperion run[3481]:   * The NumPy version is: "1.25.2"
Oct 15 11:26:30 hyperion run[3481]: and make sure that they are the versions you expect.
Oct 15 11:26:30 hyperion run[3481]: Please carefully study the documentation linked above for further help.
Oct 15 11:26:30 hyperion run[3481]: Original error was: libcblas.so.3: cannot open shared object file: No such file or directory
Oct 15 11:26:30 hyperion run[3480]: Traceback (most recent call last):
Oct 15 11:26:30 hyperion run[3480]:   File "/home/pi/homeassistant-satellite/script/run", line 13, in <module>
Oct 15 11:26:30 hyperion run[3480]:     subprocess.check_call(
Oct 15 11:26:30 hyperion run[3480]:   File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
Oct 15 11:26:30 hyperion run[3480]:     raise CalledProcessError(retcode, cmd)
Oct 15 11:26:30 hyperion run[3480]: subprocess.CalledProcessError: Command '['/home/pi/homeassistant-satellite/.venv/bin/python3', '-m', 'homeassistant_satellite', '--host', '192.168.178.156', '--token', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiMTE2OWUyNGUzYmU0NmIyYmYwMGVhYTI2ODMzNzMzNSIsImlhdCI6MTY5NzIxNzkwNiwiZXhwIjoyMDEyNTc3OTA2fQ.pDTqt01wj_JHyRJdqo2qXrOaHLVF5NteOqOtqD71Ou8', '--mic-device', 'plughw:CARD=S330', '--snd-device', 'plughw:CARD=S330', '--vad', 'silero', '--noise-suppression', '1']' returned non-zero exit status 255.
Oct 15 11:26:30 hyperion systemd[1]: homeassistant-satellite.service: Main process exited, code=exited, status=1/FAILURE
Oct 15 11:26:30 hyperion systemd[1]: homeassistant-satellite.service: Failed with result 'exit-code'.`

**Comment by chatziko** [comment]
try `sudo apt install libatlas3-base`

**Comment by cburghardt** [comment]
Then we are at the following error:

ERROR:__main__:Unexpected error in _mic_proc
Traceback (most recent call last):
  File "/home/pi/homeassistant-satellite/homeassistant_satellite/__main__.py", line 276, in _mic_proc
    vad = SileroVoiceActivityDetector(args.vad_model)
  File "/home/pi/homeassistant-satellite/homeassistant_satellite/vad.py", line 39, in __init__
    self.session = onnxruntime.InferenceSession(
  File "/home/pi/homeassistant-satellite/.venv/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/pi/homeassistant-satellite/.venv/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 368, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /home/pi/homeassistant-satellite/homeassistant_satellite/models/silero_vad.onnx failed:/home/pi/Documents/ort/build/onnxruntime/onnxruntime/core/graph/model_load_utils.h:47 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::__cxx11::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 16 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx is till opset 15.

Traceback (most recent call last):
  File "/home/pi/homeassistant-satellite/script/run", line 13, in <module>
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)

**Comment by chatziko** [comment]
Hm, it looks like your pip install picked onnxruntime==1.10.0 from https://synesthesiam.github.io/prebuilt-apps/, cause you run 32bit arm and pypi only has arm64 wheels.

But this is an old version and likely doesn't supoprt the current silero model. I tried to install onnxruntime==1.10.0 on my pi and I get the same error.

@synesthesiam : maybe you can upload a new onnxruntime build for armv7l?

**Comment by stu247** [comment]
Hi @synesthesiam , could you please upload onnxruntime-1.11.0 for armv7l?

**Comment by synesthesiam** [comment]
I'm working on new 32-bit builds for onnxruntime. I really wish Python didn't require a different wheel for every version.
