### ISSUE TITLE
No reconnect when home assistant was rebooted

### ISSUE THREAD

**Issue by stalakerob** [synesthesiam/homeassistant-satellite#48]
When I reboot home assistant, ha-satellite cannot reconnect to HA after it has rebooted. Its caught in a loop with the following error:

`Oct 22 15:47:26 raspi3b run[747]: ERROR:asyncio:Task exception was never retrieved

Oct 22 15:47:26 raspi3b run[747]: future: <Task finished name='Task-328149' coro=<ClientWebSocketResponse.send_bytes() done, defined at /home/pi/homeassistant-satellite/.venv/lib/python3.9/site-packages/aiohttp/client_ws.py:153> exception=ConnectionResetError('Cannot write to closing transport')>
Oct 22 15:47:26 raspi3b run[747]: Traceback (most recent call last):
Oct 22 15:47:26 raspi3b run[747]:   File "/home/pi/homeassistant-satellite/.venv/lib/python3.9/site-packages/aiohttp/client_ws.py", line 156, in send_bytes
Oct 22 15:47:26 raspi3b run[747]:     await self._writer.send(data, binary=True, compress=compress)
Oct 22 15:47:26 raspi3b run[747]:   File "/home/pi/homeassistant-satellite/.venv/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 688, in send
Oct 22 15:47:26 raspi3b run[747]:     await self._send_frame(message, WSMsgType.BINARY, compress)
Oct 22 15:47:26 raspi3b run[747]:   File "/home/pi/homeassistant-satellite/.venv/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 601, in _send_frame
Oct 22 15:47:26 raspi3b run[747]:     raise ConnectionResetError("Cannot write to closing transport")
Oct 22 15:47:26 raspi3b run[747]: ConnectionResetError: Cannot write to closing transport
`

**Comment by cburghardt** [comment]
Same as #28

**Comment by Emile86** [comment]
Same problem here and also very annoying that speaker keep making sound and i have to reboot rasperry pi with connected speaker to it otherwise it will keep playing sound

**Comment by Emile86** [comment]
> I had that once too that it played the awake-sound over and over.
> 
> > and i have to reboot rasberry pi
> 
> Does "sudo systemctl restart homeassistant-satellite.service" not fix it?

Yes it's also possible but in all cases it requires me to manually interact with the raspberry.
And if I'm not at home then is my wife not so happy :)

**Comment by bouton** [comment]
Yep. Happens with me as well.

**Comment by j3mu5** [comment]
Yes, this behaviour currently prevents me from testing the reliability of the system.
