### ISSUE TITLE
[Rpi5] Error on run (cannot find PCM)

### ISSUE THREAD

**Issue by lightsabata** [synesthesiam/homeassistant-satellite#75]
hi !
Today i've just receive a brand new Raspberry pi 5 to repace a rpi4.
unfortunalty, after installation when i launch the run script it crash with this message.
(if i am not  mistaken, it seems to be related to a sound card not found.
So i've test with --mic-device arguement but the same error occur (chaning "Unknown PCM input" to "Unknown PCM MYDEVICE"
here's the log:
```
USER@raspberry:~/homeassistant-satellite $ script/run --host MYHAHOST --token MYTOKEN
**ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM input**
arecord: main:831: erreur à l'ouverture audio : Aucun fichier ou dossier de ce type
ERROR:root:Unexpected error in mic_task_entry
Traceback (most recent call last):
  File "/home/USER/homeassistant-satellite/homeassistant_satellite/mic_process.py", line 361, in mic_task_entry
    async for ts_chunk in mic_stream:
  File "/home/USER/homeassistant-satellite/homeassistant_satellite/mic_process.py", line 200, in _skip_mic_state_pipe
    async for ts_chunk in mic_input:
  File "/home/USER/homeassistant-satellite/homeassistant_satellite/mic_process.py", line 200, in _skip_mic_state_pipe
    async for ts_chunk in mic_input:
  File "/home/USER/homeassistant-satellite/homeassistant_satellite/mic_process.py", line 52, in __ensure_running_pipe
    async for ts_chunk in mic_input:
  File "/home/USER/homeassistant-satellite/homeassistant_satellite/mic_record.py", line 101, in record_subprocess
    chunk = await proc.stdout.readexactly(bytes_per_chunk)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 726, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 960 expected bytes
Traceback (most recent call last):
  File "/home/USER/homeassistant-satellite/script/run", line 13, in <module>
    subprocess.check_call(
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/USER/homeassistant-satellite/.venv/bin/python3', '-m', 'homeassistant_satellite', '--host', 'MYHAHOST', '--token', 'MYTOKEN' returned non-zero exit status 255.
```

i dont know why since it work without any issue on rpi4 and i use the same alsa configuration and same mic on both
Is anybody has encountered this issue with a rpi 5 ?
thanks

**Comment by lightsabata** [comment]
after some reseach i aperar that i misconfigured my alsa config file.
so no related to homeassistant-satellite
sorry for spamming
